export const SHOP_INFO = 'SHOP_INFO';
export const CHANGE_SHOP_INFO = 'CHANGE_SHOP_INFO';
export const CHANGE_PHONE_LOGIN = 'CHANGE_PHONE_LOGIN';
export const CHANHE_COUPON_MODAL = 'CHANHE_COUPON_MODAL';