// export { default as Button } from './button';
export { default as Image } from './image';
// export { default as Modal } from './modal/modal';
// export { default as PriceBox } from './priceBox';
// export { default as Swiper } from './swiper';
// export { default as Tab } from './tab';
export { default as Title } from './title';
// export { default as AllPageTitle } from './title/allPage';
// export { default as BottomTab } from './bottomTab';
// export { default as Radio } from './radio';
// export { default as Message } from './message/index';
// export { default as OpenTips } from './openTips/index';
// export { default as Guide } from './guide/index';
// export { default as ReviewListComponent } from './reviewListComponent/index';